Edited POST route to included database integration
software-students-fall2021/project-setup-pengfan-z pull request #73
Opened 2021-11-16 01:12 UTC by avimadsen

2021-11-16 17:37 UTC, Hans-Hu requested changes

2021-11-16 17:37 UTC, Hans-Hu commented on back-end/routes/courseComments.js
> +            currCourse.comments.push(comment);
I think there should be a save here
```suggestion
            currCourse.comments.push(comment);
            await currCourse.save();
```

2021-11-17 04:07 UTC, PengfanZ approved these changes

2021-11-17 20:42 UTC, PengfanZ approved these changes

2021-11-17 20:43 UTC, PengfanZ approved these changes

2021-11-17 23:42 UTC, PengfanZ approved these changes
Looks good.

2021-11-18 00:30 UTC, Hans-Hu approved these changes

2021-11-18 00:31 UTC, merged